<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Destinations.php');
	include_once(__DIR__ . '/Destinations_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Destinations');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Destinations';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Destinations`.`id`" => "id",
		"`Destinations`.`hostname`" => "hostname",
		"`Destinations`.`type`" => "type",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "client",
		"`Destinations`.`space`" => "space",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Destinations`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Clients1`.`name`',
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Destinations`.`id`" => "id",
		"`Destinations`.`hostname`" => "hostname",
		"`Destinations`.`type`" => "type",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "client",
		"`Destinations`.`space`" => "space",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Destinations`.`id`" => "ID",
		"`Destinations`.`hostname`" => "Hostname",
		"`Destinations`.`type`" => "Type",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "Client",
		"`Destinations`.`space`" => "Capacity",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Destinations`.`id`" => "id",
		"`Destinations`.`hostname`" => "hostname",
		"`Destinations`.`type`" => "type",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "client",
		"`Destinations`.`space`" => "space",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['client' => 'Client', ];

	$x->QueryFrom = "`Destinations` LEFT JOIN `Clients` as Clients1 ON `Clients1`.`id`=`Destinations`.`client` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = (getLoggedAdmin() !== false);
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Destinations_view.php';
	$x->TableTitle = 'Destinations';
	$x->TableIcon = 'resources/table_icons/arrow_branch.png';
	$x->PrimaryKey = '`Destinations`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Hostname', 'Type', 'Client', 'Capacity', ];
	$x->ColFieldName = ['hostname', 'type', 'client', 'space', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Destinations_templateTV.html';
	$x->SelectedTemplate = 'templates/Destinations_templateTVS.html';
	$x->TemplateDV = 'templates/Destinations_templateDV.html';
	$x->TemplateDVP = 'templates/Destinations_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Destinations_init
	$render = true;
	if(function_exists('Destinations_init')) {
		$args = [];
		$render = Destinations_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Destinations_header
	$headerCode = '';
	if(function_exists('Destinations_header')) {
		$args = [];
		$headerCode = Destinations_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Destinations_footer
	$footerCode = '';
	if(function_exists('Destinations_footer')) {
		$args = [];
		$footerCode = Destinations_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
