<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Endpoints.php');
	include_once(__DIR__ . '/Endpoints_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Endpoints');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Endpoints';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Endpoints`.`id`" => "id",
		"`Endpoints`.`hostname`" => "hostname",
		"`Endpoints`.`notes`" => "notes",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Clientid */" => "clientid",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Endpoints`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Clients1`.`name`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Endpoints`.`id`" => "id",
		"`Endpoints`.`hostname`" => "hostname",
		"`Endpoints`.`notes`" => "notes",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Clientid */" => "clientid",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Endpoints`.`id`" => "ID",
		"`Endpoints`.`hostname`" => "Hostname",
		"`Endpoints`.`notes`" => "Notes",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Clientid */" => "Clientid",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Endpoints`.`id`" => "id",
		"`Endpoints`.`hostname`" => "hostname",
		"`Endpoints`.`notes`" => "notes",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Clientid */" => "clientid",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['clientid' => 'Clientid', ];

	$x->QueryFrom = "`Endpoints` LEFT JOIN `Clients` as Clients1 ON `Clients1`.`id`=`Endpoints`.`clientid` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Endpoints_view.php';
	$x->TableTitle = 'Endpoints';
	$x->TableIcon = 'resources/table_icons/dns_setting.png';
	$x->PrimaryKey = '`Endpoints`.`id`';
	$x->DefaultSortField = '4';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Hostname', 'Notes', 'Clientid', ];
	$x->ColFieldName = ['hostname', 'notes', 'clientid', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Endpoints_templateTV.html';
	$x->SelectedTemplate = 'templates/Endpoints_templateTVS.html';
	$x->TemplateDV = 'templates/Endpoints_templateDV.html';
	$x->TemplateDVP = 'templates/Endpoints_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Endpoints_init
	$render = true;
	if(function_exists('Endpoints_init')) {
		$args = [];
		$render = Endpoints_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Endpoints_header
	$headerCode = '';
	if(function_exists('Endpoints_header')) {
		$args = [];
		$headerCode = Endpoints_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Endpoints_footer
	$footerCode = '';
	if(function_exists('Endpoints_footer')) {
		$args = [];
		$footerCode = Endpoints_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
