<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Jobs.php');
	include_once(__DIR__ . '/Jobs_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Jobs');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Jobs';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Jobs`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "client",
		"IF(    CHAR_LENGTH(`Software1`.`name`), CONCAT_WS('',   `Software1`.`name`), '') /* Software */" => "software",
		"IF(    CHAR_LENGTH(`Endpoints1`.`hostname`), CONCAT_WS('',   `Endpoints1`.`hostname`), '') /* Endpoint */" => "endpoint",
		"IF(    CHAR_LENGTH(`Methods1`.`name`) || CHAR_LENGTH(`Software2`.`name`), CONCAT_WS('',   `Methods1`.`name`, ' - ', `Software2`.`name`), '') /* Method */" => "method",
		"IF(    CHAR_LENGTH(`Destinations1`.`type`) || CHAR_LENGTH(`Destinations1`.`id`), CONCAT_WS('',   `Destinations1`.`type`, '- ', `Destinations1`.`id`), '') /* Destination */" => "destination",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Jobs`.`id`',
		2 => '`Clients1`.`name`',
		3 => '`Software1`.`name`',
		4 => '`Endpoints1`.`hostname`',
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Jobs`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "client",
		"IF(    CHAR_LENGTH(`Software1`.`name`), CONCAT_WS('',   `Software1`.`name`), '') /* Software */" => "software",
		"IF(    CHAR_LENGTH(`Endpoints1`.`hostname`), CONCAT_WS('',   `Endpoints1`.`hostname`), '') /* Endpoint */" => "endpoint",
		"IF(    CHAR_LENGTH(`Methods1`.`name`) || CHAR_LENGTH(`Software2`.`name`), CONCAT_WS('',   `Methods1`.`name`, ' - ', `Software2`.`name`), '') /* Method */" => "method",
		"IF(    CHAR_LENGTH(`Destinations1`.`type`) || CHAR_LENGTH(`Destinations1`.`id`), CONCAT_WS('',   `Destinations1`.`type`, '- ', `Destinations1`.`id`), '') /* Destination */" => "destination",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Jobs`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "Client",
		"IF(    CHAR_LENGTH(`Software1`.`name`), CONCAT_WS('',   `Software1`.`name`), '') /* Software */" => "Software",
		"IF(    CHAR_LENGTH(`Endpoints1`.`hostname`), CONCAT_WS('',   `Endpoints1`.`hostname`), '') /* Endpoint */" => "Endpoint",
		"IF(    CHAR_LENGTH(`Methods1`.`name`) || CHAR_LENGTH(`Software2`.`name`), CONCAT_WS('',   `Methods1`.`name`, ' - ', `Software2`.`name`), '') /* Method */" => "Method",
		"IF(    CHAR_LENGTH(`Destinations1`.`type`) || CHAR_LENGTH(`Destinations1`.`id`), CONCAT_WS('',   `Destinations1`.`type`, '- ', `Destinations1`.`id`), '') /* Destination */" => "Destination",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Jobs`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Clients1`.`name`), CONCAT_WS('',   `Clients1`.`name`), '') /* Client */" => "client",
		"IF(    CHAR_LENGTH(`Software1`.`name`), CONCAT_WS('',   `Software1`.`name`), '') /* Software */" => "software",
		"IF(    CHAR_LENGTH(`Endpoints1`.`hostname`), CONCAT_WS('',   `Endpoints1`.`hostname`), '') /* Endpoint */" => "endpoint",
		"IF(    CHAR_LENGTH(`Methods1`.`name`) || CHAR_LENGTH(`Software2`.`name`), CONCAT_WS('',   `Methods1`.`name`, ' - ', `Software2`.`name`), '') /* Method */" => "method",
		"IF(    CHAR_LENGTH(`Destinations1`.`type`) || CHAR_LENGTH(`Destinations1`.`id`), CONCAT_WS('',   `Destinations1`.`type`, '- ', `Destinations1`.`id`), '') /* Destination */" => "destination",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['client' => 'Client', 'software' => 'Software', 'endpoint' => 'Endpoint', 'method' => 'Method', 'destination' => 'Destination', ];

	$x->QueryFrom = "`Jobs` LEFT JOIN `Clients` as Clients1 ON `Clients1`.`id`=`Jobs`.`client` LEFT JOIN `Software` as Software1 ON `Software1`.`id`=`Jobs`.`software` LEFT JOIN `Endpoints` as Endpoints1 ON `Endpoints1`.`id`=`Jobs`.`endpoint` LEFT JOIN `Methods` as Methods1 ON `Methods1`.`id`=`Jobs`.`method` LEFT JOIN `Software` as Software2 ON `Software2`.`id`=`Methods1`.`software` LEFT JOIN `Destinations` as Destinations1 ON `Destinations1`.`id`=`Jobs`.`destination` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Jobs_view.php';
	$x->TableTitle = 'Jobs';
	$x->TableIcon = 'resources/table_icons/cog.png';
	$x->PrimaryKey = '`Jobs`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Client', 'Software', 'Endpoint', 'Method', 'Destination', ];
	$x->ColFieldName = ['client', 'software', 'endpoint', 'method', 'destination', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Jobs_templateTV.html';
	$x->SelectedTemplate = 'templates/Jobs_templateTVS.html';
	$x->TemplateDV = 'templates/Jobs_templateDV.html';
	$x->TemplateDVP = 'templates/Jobs_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Jobs_init
	$render = true;
	if(function_exists('Jobs_init')) {
		$args = [];
		$render = Jobs_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Jobs_header
	$headerCode = '';
	if(function_exists('Jobs_header')) {
		$args = [];
		$headerCode = Jobs_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Jobs_footer
	$footerCode = '';
	if(function_exists('Jobs_footer')) {
		$args = [];
		$footerCode = Jobs_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
