<?php

// Data functions (insert, update, delete, form) for table Jobs

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function Jobs_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Jobs');
	if(!$arrPerm['insert']) return false;

	$data = [
		'client' => Request::lookup('client', ''),
		'software' => Request::lookup('software', ''),
		'endpoint' => Request::lookup('endpoint', ''),
		'method' => Request::lookup('method', ''),
		'destination' => Request::lookup('destination', ''),
	];


	// hook: Jobs_before_insert
	if(function_exists('Jobs_before_insert')) {
		$args = [];
		if(!Jobs_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Jobs', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Jobs', $recID, calculated_fields()['Jobs']);

	// hook: Jobs_after_insert
	if(function_exists('Jobs_after_insert')) {
		$res = sql("SELECT * FROM `Jobs` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Jobs_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Jobs', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Jobs_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Jobs_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Jobs_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Jobs', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Jobs_before_delete
	if(function_exists('Jobs_before_delete')) {
		$args = [];
		if(!Jobs_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Log
	$res = sql("SELECT `id` FROM `Jobs` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Log` WHERE `job`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Log', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Log', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Jobs_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Jobs_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Jobs` WHERE `id`='{$selected_id}'", $eo);

	// hook: Jobs_after_delete
	if(function_exists('Jobs_after_delete')) {
		$args = [];
		Jobs_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Jobs' AND `pkValue`='{$selected_id}'", $eo);
}

function Jobs_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Jobs', $selected_id, 'edit')) return false;

	$data = [
		'client' => Request::lookup('client', ''),
		'software' => Request::lookup('software', ''),
		'endpoint' => Request::lookup('endpoint', ''),
		'method' => Request::lookup('method', ''),
		'destination' => Request::lookup('destination', ''),
	];

	// get existing values
	$old_data = getRecord('Jobs', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Jobs_before_update
	if(function_exists('Jobs_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Jobs_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Jobs', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Jobs_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Jobs', $data['selectedID'], calculated_fields()['Jobs']);

	// hook: Jobs_after_update
	if(function_exists('Jobs_after_update')) {
		$res = sql("SELECT * FROM `Jobs` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Jobs_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Jobs' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Jobs_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Jobs');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_client = Request::val('filterer_client');
	$filterer_software = Request::val('filterer_software');
	$filterer_endpoint = Request::val('filterer_endpoint');
	$filterer_method = Request::val('filterer_method');
	$filterer_destination = Request::val('filterer_destination');

	// populate filterers, starting from children to grand-parents
	if($filterer_endpoint && !$filterer_client) $filterer_client = sqlValue("select clientid from Endpoints where id='" . makeSafe($filterer_endpoint) . "'");
	if($filterer_method && !$filterer_software) $filterer_software = sqlValue("select software from Methods where id='" . makeSafe($filterer_method) . "'");
	if($filterer_destination && !$filterer_client) $filterer_client = sqlValue("select client from Destinations where id='" . makeSafe($filterer_destination) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: client
	$combo_client = new DataCombo;
	// combobox: software
	$combo_software = new DataCombo;
	// combobox: endpoint, filterable by: client
	$combo_endpoint = new DataCombo;
	// combobox: method, filterable by: software
	$combo_method = new DataCombo;
	// combobox: destination, filterable by: client
	$combo_destination = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('Jobs', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Jobs', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Jobs', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Jobs` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Jobs_view.php', false);
		}
		$combo_client->SelectedData = $row['client'];
		$combo_software->SelectedData = $row['software'];
		$combo_endpoint->SelectedData = $row['endpoint'];
		$combo_method->SelectedData = $row['method'];
		$combo_destination->SelectedData = $row['destination'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_client->SelectedData = $filterer_client;
		$combo_software->SelectedData = $filterer_software;
		$combo_endpoint->SelectedData = $filterer_endpoint;
		$combo_method->SelectedData = $filterer_method;
		$combo_destination->SelectedData = $filterer_destination;
	}
	$combo_client->HTML = '<span id="client-container' . $rnd1 . '"></span><input type="hidden" name="client" id="client' . $rnd1 . '" value="' . html_attr($combo_client->SelectedData) . '">';
	$combo_client->MatchText = '<span id="client-container-readonly' . $rnd1 . '"></span><input type="hidden" name="client" id="client' . $rnd1 . '" value="' . html_attr($combo_client->SelectedData) . '">';
	$combo_software->HTML = '<span id="software-container' . $rnd1 . '"></span><input type="hidden" name="software" id="software' . $rnd1 . '" value="' . html_attr($combo_software->SelectedData) . '">';
	$combo_software->MatchText = '<span id="software-container-readonly' . $rnd1 . '"></span><input type="hidden" name="software" id="software' . $rnd1 . '" value="' . html_attr($combo_software->SelectedData) . '">';
	$combo_endpoint->HTML = '<span id="endpoint-container' . $rnd1 . '"></span><input type="hidden" name="endpoint" id="endpoint' . $rnd1 . '" value="' . html_attr($combo_endpoint->SelectedData) . '">';
	$combo_endpoint->MatchText = '<span id="endpoint-container-readonly' . $rnd1 . '"></span><input type="hidden" name="endpoint" id="endpoint' . $rnd1 . '" value="' . html_attr($combo_endpoint->SelectedData) . '">';
	$combo_method->HTML = '<span id="method-container' . $rnd1 . '"></span><input type="hidden" name="method" id="method' . $rnd1 . '" value="' . html_attr($combo_method->SelectedData) . '">';
	$combo_method->MatchText = '<span id="method-container-readonly' . $rnd1 . '"></span><input type="hidden" name="method" id="method' . $rnd1 . '" value="' . html_attr($combo_method->SelectedData) . '">';
	$combo_destination->HTML = '<span id="destination-container' . $rnd1 . '"></span><input type="hidden" name="destination" id="destination' . $rnd1 . '" value="' . html_attr($combo_destination->SelectedData) . '">';
	$combo_destination->MatchText = '<span id="destination-container-readonly' . $rnd1 . '"></span><input type="hidden" name="destination" id="destination' . $rnd1 . '" value="' . html_attr($combo_destination->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_client__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['client'] : htmlspecialchars($filterer_client, ENT_QUOTES)); ?>"};
		AppGini.current_software__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['software'] : htmlspecialchars($filterer_software, ENT_QUOTES)); ?>"};
		AppGini.current_endpoint__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['endpoint'] : htmlspecialchars($filterer_endpoint, ENT_QUOTES)); ?>"};
		AppGini.current_method__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['method'] : htmlspecialchars($filterer_method, ENT_QUOTES)); ?>"};
		AppGini.current_destination__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['destination'] : htmlspecialchars($filterer_destination, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(client_reload__RAND__) == 'function') client_reload__RAND__();
				if(typeof(software_reload__RAND__) == 'function') software_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(endpoint_reload__RAND__) == \'function\') endpoint_reload__RAND__(AppGini.current_client__RAND__.value);' : ''); ?>
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(method_reload__RAND__) == \'function\') method_reload__RAND__(AppGini.current_software__RAND__.value);' : ''); ?>
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(destination_reload__RAND__) == \'function\') destination_reload__RAND__(AppGini.current_client__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function client_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#client-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_client__RAND__.value, t: 'Jobs', f: 'client' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="client"]').val(resp.results[0].id);
							$j('[id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

						if(typeof(endpoint_reload__RAND__) == 'function') endpoint_reload__RAND__(AppGini.current_client__RAND__.value);
						if(typeof(destination_reload__RAND__) == 'function') destination_reload__RAND__(AppGini.current_client__RAND__.value);

							if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Jobs', f: 'client' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_client__RAND__.value = e.added.id;
				AppGini.current_client__RAND__.text = e.added.text;
				$j('[name="client"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

						if(typeof(endpoint_reload__RAND__) == 'function') endpoint_reload__RAND__(AppGini.current_client__RAND__.value);
						if(typeof(destination_reload__RAND__) == 'function') destination_reload__RAND__(AppGini.current_client__RAND__.value);

				if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
			});

			if(!$j("#client-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_client__RAND__.value, t: 'Jobs', f: 'client' },
					success: function(resp) {
						$j('[name="client"]').val(resp.results[0].id);
						$j('[id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

						if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_client__RAND__.value, t: 'Jobs', f: 'client' },
				success: function(resp) {
					$j('[id=client-container__RAND__], [id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

					if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function software_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#software-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_software__RAND__.value, t: 'Jobs', f: 'software' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="software"]').val(resp.results[0].id);
							$j('[id=software-container-readonly__RAND__]').html('<span class="match-text" id="software-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Software_view_parent]').hide(); } else { $j('.btn[id=Software_view_parent]').show(); }

						if(typeof(method_reload__RAND__) == 'function') method_reload__RAND__(AppGini.current_software__RAND__.value);

							if(typeof(software_update_autofills__RAND__) == 'function') software_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Jobs', f: 'software' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_software__RAND__.value = e.added.id;
				AppGini.current_software__RAND__.text = e.added.text;
				$j('[name="software"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Software_view_parent]').hide(); } else { $j('.btn[id=Software_view_parent]').show(); }

						if(typeof(method_reload__RAND__) == 'function') method_reload__RAND__(AppGini.current_software__RAND__.value);

				if(typeof(software_update_autofills__RAND__) == 'function') software_update_autofills__RAND__();
			});

			if(!$j("#software-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_software__RAND__.value, t: 'Jobs', f: 'software' },
					success: function(resp) {
						$j('[name="software"]').val(resp.results[0].id);
						$j('[id=software-container-readonly__RAND__]').html('<span class="match-text" id="software-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Software_view_parent]').hide(); } else { $j('.btn[id=Software_view_parent]').show(); }

						if(typeof(software_update_autofills__RAND__) == 'function') software_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_software__RAND__.value, t: 'Jobs', f: 'software' },
				success: function(resp) {
					$j('[id=software-container__RAND__], [id=software-container-readonly__RAND__]').html('<span class="match-text" id="software-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Software_view_parent]').hide(); } else { $j('.btn[id=Software_view_parent]').show(); }

					if(typeof(software_update_autofills__RAND__) == 'function') software_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function endpoint_reload__RAND__(filterer_client) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#endpoint-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_client: filterer_client, id: AppGini.current_endpoint__RAND__.value, t: 'Jobs', f: 'endpoint' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="endpoint"]').val(resp.results[0].id);
							$j('[id=endpoint-container-readonly__RAND__]').html('<span class="match-text" id="endpoint-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }


							if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_client: filterer_client, s: term, p: page, t: 'Jobs', f: 'endpoint' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_endpoint__RAND__.value = e.added.id;
				AppGini.current_endpoint__RAND__.text = e.added.text;
				$j('[name="endpoint"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }


				if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
			});

			if(!$j("#endpoint-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_endpoint__RAND__.value, t: 'Jobs', f: 'endpoint' },
					success: function(resp) {
						$j('[name="endpoint"]').val(resp.results[0].id);
						$j('[id=endpoint-container-readonly__RAND__]').html('<span class="match-text" id="endpoint-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }

						if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_endpoint__RAND__.value, t: 'Jobs', f: 'endpoint' },
				success: function(resp) {
					$j('[id=endpoint-container__RAND__], [id=endpoint-container-readonly__RAND__]').html('<span class="match-text" id="endpoint-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }

					if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function method_reload__RAND__(filterer_software) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#method-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_software: filterer_software, id: AppGini.current_method__RAND__.value, t: 'Jobs', f: 'method' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="method"]').val(resp.results[0].id);
							$j('[id=method-container-readonly__RAND__]').html('<span class="match-text" id="method-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Methods_view_parent]').hide(); } else { $j('.btn[id=Methods_view_parent]').show(); }


							if(typeof(method_update_autofills__RAND__) == 'function') method_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_software: filterer_software, s: term, p: page, t: 'Jobs', f: 'method' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_method__RAND__.value = e.added.id;
				AppGini.current_method__RAND__.text = e.added.text;
				$j('[name="method"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Methods_view_parent]').hide(); } else { $j('.btn[id=Methods_view_parent]').show(); }


				if(typeof(method_update_autofills__RAND__) == 'function') method_update_autofills__RAND__();
			});

			if(!$j("#method-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_method__RAND__.value, t: 'Jobs', f: 'method' },
					success: function(resp) {
						$j('[name="method"]').val(resp.results[0].id);
						$j('[id=method-container-readonly__RAND__]').html('<span class="match-text" id="method-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Methods_view_parent]').hide(); } else { $j('.btn[id=Methods_view_parent]').show(); }

						if(typeof(method_update_autofills__RAND__) == 'function') method_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_method__RAND__.value, t: 'Jobs', f: 'method' },
				success: function(resp) {
					$j('[id=method-container__RAND__], [id=method-container-readonly__RAND__]').html('<span class="match-text" id="method-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Methods_view_parent]').hide(); } else { $j('.btn[id=Methods_view_parent]').show(); }

					if(typeof(method_update_autofills__RAND__) == 'function') method_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function destination_reload__RAND__(filterer_client) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#destination-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_client: filterer_client, id: AppGini.current_destination__RAND__.value, t: 'Jobs', f: 'destination' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="destination"]').val(resp.results[0].id);
							$j('[id=destination-container-readonly__RAND__]').html('<span class="match-text" id="destination-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Destinations_view_parent]').hide(); } else { $j('.btn[id=Destinations_view_parent]').show(); }


							if(typeof(destination_update_autofills__RAND__) == 'function') destination_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_client: filterer_client, s: term, p: page, t: 'Jobs', f: 'destination' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_destination__RAND__.value = e.added.id;
				AppGini.current_destination__RAND__.text = e.added.text;
				$j('[name="destination"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Destinations_view_parent]').hide(); } else { $j('.btn[id=Destinations_view_parent]').show(); }


				if(typeof(destination_update_autofills__RAND__) == 'function') destination_update_autofills__RAND__();
			});

			if(!$j("#destination-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_destination__RAND__.value, t: 'Jobs', f: 'destination' },
					success: function(resp) {
						$j('[name="destination"]').val(resp.results[0].id);
						$j('[id=destination-container-readonly__RAND__]').html('<span class="match-text" id="destination-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Destinations_view_parent]').hide(); } else { $j('.btn[id=Destinations_view_parent]').show(); }

						if(typeof(destination_update_autofills__RAND__) == 'function') destination_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_destination__RAND__.value, t: 'Jobs', f: 'destination' },
				success: function(resp) {
					$j('[id=destination-container__RAND__], [id=destination-container-readonly__RAND__]').html('<span class="match-text" id="destination-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Destinations_view_parent]').hide(); } else { $j('.btn[id=Destinations_view_parent]').show(); }

					if(typeof(destination_update_autofills__RAND__) == 'function') destination_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Jobs_templateDV.html';
	$templateCode = @file_get_contents($template_file);

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Job details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Jobs_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Jobs_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Jobs_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#client').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#client_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#software').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#software_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#endpoint').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#endpoint_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#method').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#method_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#destination').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#destination_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(client)%%>', $combo_client->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(client)%%>', $combo_client->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(client)%%>', urlencode($combo_client->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(software)%%>', $combo_software->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(software)%%>', $combo_software->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(software)%%>', urlencode($combo_software->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(endpoint)%%>', $combo_endpoint->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(endpoint)%%>', $combo_endpoint->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(endpoint)%%>', urlencode($combo_endpoint->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(method)%%>', $combo_method->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(method)%%>', $combo_method->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(method)%%>', urlencode($combo_method->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(destination)%%>', $combo_destination->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(destination)%%>', $combo_destination->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(destination)%%>', urlencode($combo_destination->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['client' => ['Clients', 'Client'], 'software' => ['Software', 'Software'], 'endpoint' => ['Endpoints', 'Endpoint'], 'method' => ['Methods', 'Method'], 'destination' => ['Destinations', 'Destination'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(client)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(software)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(endpoint)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(method)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(destination)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', safe_html($urow['client']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', html_attr($row['client']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode($urow['client']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(software)%%>', safe_html($urow['software']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(software)%%>', html_attr($row['software']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(software)%%>', urlencode($urow['software']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(endpoint)%%>', safe_html($urow['endpoint']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(endpoint)%%>', html_attr($row['endpoint']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(endpoint)%%>', urlencode($urow['endpoint']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(method)%%>', safe_html($urow['method']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(method)%%>', html_attr($row['method']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(method)%%>', urlencode($urow['method']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(destination)%%>', safe_html($urow['destination']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(destination)%%>', html_attr($row['destination']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(destination)%%>', urlencode($urow['destination']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(client)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(software)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(software)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(endpoint)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(endpoint)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(method)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(method)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(destination)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(destination)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Jobs');
	if($selected_id) {
		$jdata = get_joined_record('Jobs', $selected_id);
		if($jdata === false) $jdata = get_defaults('Jobs');
		$rdata = $row;
	}
	$templateCode .= loadView('Jobs-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Jobs_dv
	if(function_exists('Jobs_dv')) {
		$args = [];
		Jobs_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}