<?php

// Data functions (insert, update, delete, form) for table Log

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function Log_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Log');
	if(!$arrPerm['insert']) return false;

	$data = [
		'date' => parseCode('<%%creationDate%%>', true, true),
		'user' => parseCode('<%%creatorUsername%%>', true),
		'client' => Request::lookup('client', ''),
		'endpoint' => Request::lookup('endpoint', ''),
		'job' => Request::lookup('job', ''),
		'status' => Request::val('status', ''),
		'results' => br2nl(Request::val('results', '')),
		'screenshot' => Request::fileUpload('screenshot', [
			'maxSize' => 3072000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Log', 'screenshot', 'tv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('Log', 'screenshot', Request::val('SelectedID'));
			},
		]),
		'notes' => Request::val('notes', ''),
	];


	// hook: Log_before_insert
	if(function_exists('Log_before_insert')) {
		$args = [];
		if(!Log_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Log', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Log', $recID, calculated_fields()['Log']);

	// hook: Log_after_insert
	if(function_exists('Log_after_insert')) {
		$res = sql("SELECT * FROM `Log` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Log_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Log', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Log_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Log_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Log_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Log', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Log_before_delete
	if(function_exists('Log_before_delete')) {
		$args = [];
		if(!Log_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Log` WHERE `id`='{$selected_id}'", $eo);

	// hook: Log_after_delete
	if(function_exists('Log_after_delete')) {
		$args = [];
		Log_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Log' AND `pkValue`='{$selected_id}'", $eo);
}

function Log_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Log', $selected_id, 'edit')) return false;

	$data = [
		'client' => Request::lookup('client', ''),
		'endpoint' => Request::lookup('endpoint', ''),
		'job' => Request::lookup('job', ''),
		'status' => Request::val('status', ''),
		'results' => br2nl(Request::val('results', '')),
		'screenshot' => Request::fileUpload('screenshot', [
			'maxSize' => 3072000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Log', 'screenshot', 'tv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('Log', 'screenshot', $selected_id);
			},
		]),
		'notes' => Request::val('notes', ''),
	];

	// get existing values
	$old_data = getRecord('Log', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Log_before_update
	if(function_exists('Log_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Log_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Log', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Log_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Log', $data['selectedID'], calculated_fields()['Log']);

	// hook: Log_after_update
	if(function_exists('Log_after_update')) {
		$res = sql("SELECT * FROM `Log` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Log_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Log' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Log_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Log');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_client = Request::val('filterer_client');
	$filterer_endpoint = Request::val('filterer_endpoint');
	$filterer_job = Request::val('filterer_job');

	// populate filterers, starting from children to grand-parents
	if($filterer_endpoint && !$filterer_client) $filterer_client = sqlValue("select clientid from Endpoints where id='" . makeSafe($filterer_endpoint) . "'");
	if($filterer_job && !$filterer_client) $filterer_client = sqlValue("select client from Jobs where id='" . makeSafe($filterer_job) . "'");
	if($filterer_job && !$filterer_endpoint) $filterer_endpoint = sqlValue("select endpoint from Jobs where id='" . makeSafe($filterer_job) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "dmy";
	$combo_date->MinYear = defined('Log.date.MinYear') ? constant('Log.date.MinYear') : 1900;
	$combo_date->MaxYear = defined('Log.date.MaxYear') ? constant('Log.date.MaxYear') : 2100;
	$combo_date->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: client
	$combo_client = new DataCombo;
	// combobox: endpoint, filterable by: client
	$combo_endpoint = new DataCombo;
	// combobox: job, filterable by: client,endpoint
	$combo_job = new DataCombo;
	// combobox: status
	$combo_status = new Combo;
	$combo_status->ListType = 2;
	$combo_status->MultipleSeparator = ', ';
	$combo_status->ListBoxHeight = 10;
	$combo_status->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Log.status.csv')) {
		$status_data = addslashes(implode('', @file(__DIR__ . '/hooks/Log.status.csv')));
		$combo_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($status_data))));
		$combo_status->ListData = $combo_status->ListItem;
	} else {
		$combo_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Successful;;Unsuccessful"))));
		$combo_status->ListData = $combo_status->ListItem;
	}
	$combo_status->SelectName = 'status';

	if($selected_id) {
		if(!check_record_permission('Log', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Log', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Log', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Log` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Log_view.php', false);
		}
		$combo_date->DefaultDate = $row['date'];
		$combo_client->SelectedData = $row['client'];
		$combo_endpoint->SelectedData = $row['endpoint'];
		$combo_job->SelectedData = $row['job'];
		$combo_status->SelectedData = $row['status'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_client->SelectedData = $filterer_client;
		$combo_endpoint->SelectedData = $filterer_endpoint;
		$combo_job->SelectedData = $filterer_job;
		$combo_status->SelectedText = (isset($filterField[1]) && $filterField[1] == '7' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
	}
	$combo_client->HTML = '<span id="client-container' . $rnd1 . '"></span><input type="hidden" name="client" id="client' . $rnd1 . '" value="' . html_attr($combo_client->SelectedData) . '">';
	$combo_client->MatchText = '<span id="client-container-readonly' . $rnd1 . '"></span><input type="hidden" name="client" id="client' . $rnd1 . '" value="' . html_attr($combo_client->SelectedData) . '">';
	$combo_endpoint->HTML = '<span id="endpoint-container' . $rnd1 . '"></span><input type="hidden" name="endpoint" id="endpoint' . $rnd1 . '" value="' . html_attr($combo_endpoint->SelectedData) . '">';
	$combo_endpoint->MatchText = '<span id="endpoint-container-readonly' . $rnd1 . '"></span><input type="hidden" name="endpoint" id="endpoint' . $rnd1 . '" value="' . html_attr($combo_endpoint->SelectedData) . '">';
	$combo_job->HTML = '<span id="job-container' . $rnd1 . '"></span><input type="hidden" name="job" id="job' . $rnd1 . '" value="' . html_attr($combo_job->SelectedData) . '">';
	$combo_job->MatchText = '<span id="job-container-readonly' . $rnd1 . '"></span><input type="hidden" name="job" id="job' . $rnd1 . '" value="' . html_attr($combo_job->SelectedData) . '">';
	$combo_status->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_client__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['client'] : htmlspecialchars($filterer_client, ENT_QUOTES)); ?>"};
		AppGini.current_endpoint__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['endpoint'] : htmlspecialchars($filterer_endpoint, ENT_QUOTES)); ?>"};
		AppGini.current_job__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['job'] : htmlspecialchars($filterer_job, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(client_reload__RAND__) == 'function') client_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(endpoint_reload__RAND__) == \'function\') endpoint_reload__RAND__(AppGini.current_client__RAND__.value);' : ''); ?>
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(job_reload__RAND__) == \'function\') job_reload__RAND__(AppGini.current_client__RAND__.value, AppGini.current_endpoint__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function client_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#client-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_client__RAND__.value, t: 'Log', f: 'client' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="client"]').val(resp.results[0].id);
							$j('[id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

						if(typeof(endpoint_reload__RAND__) == 'function') endpoint_reload__RAND__(AppGini.current_client__RAND__.value);

							if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Log', f: 'client' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_client__RAND__.value = e.added.id;
				AppGini.current_client__RAND__.text = e.added.text;
				$j('[name="client"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

						if(typeof(endpoint_reload__RAND__) == 'function') endpoint_reload__RAND__(AppGini.current_client__RAND__.value);

				if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
			});

			if(!$j("#client-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_client__RAND__.value, t: 'Log', f: 'client' },
					success: function(resp) {
						$j('[name="client"]').val(resp.results[0].id);
						$j('[id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

						if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_client__RAND__.value, t: 'Log', f: 'client' },
				success: function(resp) {
					$j('[id=client-container__RAND__], [id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Clients_view_parent]').hide(); } else { $j('.btn[id=Clients_view_parent]').show(); }

					if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function endpoint_reload__RAND__(filterer_client) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#endpoint-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_client: filterer_client, id: AppGini.current_endpoint__RAND__.value, t: 'Log', f: 'endpoint' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="endpoint"]').val(resp.results[0].id);
							$j('[id=endpoint-container-readonly__RAND__]').html('<span class="match-text" id="endpoint-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }

						if(typeof(job_reload__RAND__) == 'function') job_reload__RAND__($j('#client').val(), AppGini.current_endpoint__RAND__.value);

							if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_client: filterer_client, s: term, p: page, t: 'Log', f: 'endpoint' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_endpoint__RAND__.value = e.added.id;
				AppGini.current_endpoint__RAND__.text = e.added.text;
				$j('[name="endpoint"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }

						if(typeof(job_reload__RAND__) == 'function') job_reload__RAND__($j('#client').val(), AppGini.current_endpoint__RAND__.value);

				if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
			});

			if(!$j("#endpoint-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_endpoint__RAND__.value, t: 'Log', f: 'endpoint' },
					success: function(resp) {
						$j('[name="endpoint"]').val(resp.results[0].id);
						$j('[id=endpoint-container-readonly__RAND__]').html('<span class="match-text" id="endpoint-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }

						if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_endpoint__RAND__.value, t: 'Log', f: 'endpoint' },
				success: function(resp) {
					$j('[id=endpoint-container__RAND__], [id=endpoint-container-readonly__RAND__]').html('<span class="match-text" id="endpoint-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Endpoints_view_parent]').hide(); } else { $j('.btn[id=Endpoints_view_parent]').show(); }

					if(typeof(endpoint_update_autofills__RAND__) == 'function') endpoint_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function job_reload__RAND__(filterer_client, filterer_endpoint) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#job-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_client: filterer_client, filterer_endpoint: filterer_endpoint, id: AppGini.current_job__RAND__.value, t: 'Log', f: 'job' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="job"]').val(resp.results[0].id);
							$j('[id=job-container-readonly__RAND__]').html('<span class="match-text" id="job-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Jobs_view_parent]').hide(); } else { $j('.btn[id=Jobs_view_parent]').show(); }


							if(typeof(job_update_autofills__RAND__) == 'function') job_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_client: filterer_client, filterer_endpoint: filterer_endpoint, s: term, p: page, t: 'Log', f: 'job' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_job__RAND__.value = e.added.id;
				AppGini.current_job__RAND__.text = e.added.text;
				$j('[name="job"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Jobs_view_parent]').hide(); } else { $j('.btn[id=Jobs_view_parent]').show(); }


				if(typeof(job_update_autofills__RAND__) == 'function') job_update_autofills__RAND__();
			});

			if(!$j("#job-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_job__RAND__.value, t: 'Log', f: 'job' },
					success: function(resp) {
						$j('[name="job"]').val(resp.results[0].id);
						$j('[id=job-container-readonly__RAND__]').html('<span class="match-text" id="job-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Jobs_view_parent]').hide(); } else { $j('.btn[id=Jobs_view_parent]').show(); }

						if(typeof(job_update_autofills__RAND__) == 'function') job_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_job__RAND__.value, t: 'Log', f: 'job' },
				success: function(resp) {
					$j('[id=job-container__RAND__], [id=job-container-readonly__RAND__]').html('<span class="match-text" id="job-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Jobs_view_parent]').hide(); } else { $j('.btn[id=Jobs_view_parent]').show(); }

					if(typeof(job_update_autofills__RAND__) == 'function') job_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Log_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Log_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Log details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Log_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Log_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Log_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#client').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#client_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#endpoint').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#endpoint_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#job').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#job_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('input[name=status]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=status]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#results').replaceWith('<div class=\"form-control-static\" id=\"results\">' + (jQuery('#results').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#screenshot').replaceWith('<div class=\"form-control-static\" id=\"screenshot\">' + (jQuery('#screenshot').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : 
			$combo_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(client)%%>', $combo_client->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(client)%%>', $combo_client->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(client)%%>', urlencode($combo_client->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(endpoint)%%>', $combo_endpoint->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(endpoint)%%>', $combo_endpoint->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(endpoint)%%>', urlencode($combo_endpoint->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(job)%%>', $combo_job->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(job)%%>', $combo_job->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(job)%%>', urlencode($combo_job->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(status)%%>', $combo_status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(status)%%>', $combo_status->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['client' => ['Clients', 'Client'], 'endpoint' => ['Endpoints', 'Endpoint'], 'job' => ['Jobs', 'Job'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(user)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(client)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(endpoint)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(job)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(results)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(screenshot)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="screenshot" id="screenshot" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="3072000" style="max-width: calc(100% - 1.5rem);" accept="capture=camera,image/*">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($AllowUpdate && $row['screenshot'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(screenshot)%%>', '<input type="checkbox" name="screenshot_remove" id="screenshot_remove" value="1"> <label for="screenshot_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(screenshot)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(notes)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', app_datetime($row['date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(app_datetime($urow['date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(user)%%>', safe_html($urow['user']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(user)%%>', urlencode($urow['user']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', safe_html($urow['client']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', html_attr($row['client']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode($urow['client']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(endpoint)%%>', safe_html($urow['endpoint']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(endpoint)%%>', html_attr($row['endpoint']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(endpoint)%%>', urlencode($urow['endpoint']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(job)%%>', safe_html($urow['job']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(job)%%>', html_attr($row['job']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(job)%%>', urlencode($urow['job']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(results)%%>', safe_html($urow['results']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(results)%%>', safe_html($urow['results'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(results)%%>', urlencode($urow['results']), $templateCode);
		$row['screenshot'] = ($row['screenshot'] != '' ? $row['screenshot'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(screenshot)%%>', safe_html($urow['screenshot']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(screenshot)%%>', html_attr($row['screenshot']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(screenshot)%%>', urlencode($urow['screenshot']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(notes)%%>', '<textarea name="notes" id="notes" rows="5">' . safe_html(htmlspecialchars_decode($row['notes'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(notes)%%>', '<div id="notes" class="form-control-static">' . $row['notes'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(notes)%%>', nl2br($row['notes']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(notes)%%>', urlencode($urow['notes']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(user)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(user)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(client)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(endpoint)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(endpoint)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(job)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(job)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(results)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(results)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(screenshot)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(notes)%%>', '<textarea name="notes" id="notes" rows="5"></textarea>', $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Log');
	if($selected_id) {
		$jdata = get_joined_record('Log', $selected_id);
		if($jdata === false) $jdata = get_defaults('Log');
		$rdata = $row;
	}
	$templateCode .= loadView('Log-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Log_dv
	if(function_exists('Log_dv')) {
		$args = [];
		Log_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}