<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Software.php');
	include_once(__DIR__ . '/Software_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Software');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Software';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Software`.`id`" => "id",
		"`Software`.`name`" => "name",
		"`Software`.`notes`" => "notes",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Software`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Software`.`id`" => "id",
		"`Software`.`name`" => "name",
		"`Software`.`notes`" => "notes",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Software`.`id`" => "ID",
		"`Software`.`name`" => "Name",
		"`Software`.`notes`" => "Notes",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Software`.`id`" => "id",
		"`Software`.`name`" => "name",
		"`Software`.`notes`" => "notes",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Software` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = (getLoggedAdmin() !== false);
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Software_view.php';
	$x->TableTitle = 'Software';
	$x->TableIcon = 'resources/table_icons/cog_edit.png';
	$x->PrimaryKey = '`Software`.`id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Name', 'Notes', ];
	$x->ColFieldName = ['name', 'notes', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Software_templateTV.html';
	$x->SelectedTemplate = 'templates/Software_templateTVS.html';
	$x->TemplateDV = 'templates/Software_templateDV.html';
	$x->TemplateDVP = 'templates/Software_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Software_init
	$render = true;
	if(function_exists('Software_init')) {
		$args = [];
		$render = Software_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Software_header
	$headerCode = '';
	if(function_exists('Software_header')) {
		$args = [];
		$headerCode = Software_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Software_footer
	$footerCode = '';
	if(function_exists('Software_footer')) {
		$args = [];
		$footerCode = Software_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
